version: '3.8'
services:
  sam-app:
    image: amazon/aws-sam-cli-build-image-nodejs14.x
    environment:
      - AWS_REGION=us-east-1
      - SAM_ENV=development
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - .:/var/task
